# -*- coding: utf-8 -*-
"""hate_speech_detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/arghadipdutta/hate-speech-detection.b3c453d3-3b45-4a53-afbc-8872b03081e9.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260427/auto/storage/goog4_request%26X-Goog-Date%3D20260427T181849Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3Dcd545707b2307c6c9cee052b597e5b7828471b889a603b11dccae05328100ad1c6935183009357d1eaa67cea16f6c457c393c56ba0f3b41eb48ca0d579b62a41e8ffd8c62f44ae5880e6aa38900ee92a81fd9509f7e19ee2639ac1902c46dcbbefd3b4f7b47e34a6934f6d20b8aed672a07af3bfeb946c8c4fb4d5490a9c3b3780b285e8f655f15bdad289ed5a1901042af5012e39156f78c0a85f8220fd6e6c4fba2efa63f5f043a55fa8b00b1f6a0905556fc3495901a63c783facab835a0b8a6b0ee7ce80a9545650b05d7d8efa30d49061d250c0799c6311788d659d3d74e33561b65bcc6718569f71ea88ab9669d5c63605b0f418f3257a435c60355360
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
waalbannyantudre_hate_speech_detection_curated_dataset_path = kagglehub.dataset_download('waalbannyantudre/hate-speech-detection-curated-dataset')

print('Data source import complete.')

import kagglehub

# Download latest version
path = kagglehub.dataset_download("waalbannyantudre/hate-speech-detection-curated-dataset")

print("Path to dataset files:", path)

import os

path = "/kaggle/input/datasets/waalbannyantudre/hate-speech-detection-curated-dataset"
print(os.listdir(path))

import pandas as pd
import numpy as np

/kaggle/input/datasets/waalbannyantudre/hate-speech-detection-curated-dataset/HateSpeechDatasetBalanced.csv

path1="/kaggle/input/datasets/waalbannyantudre/hate-speech-detection-curated-dataset/HateSpeechDataset.csv"

new_df=pd.read_csv('/kaggle/input/datasets/waalbannyantudre/hate-speech-detection-curated-dataset/HateSpeechDatasetBalanced.csv')

new_df['Label'].value_counts()

new_df.head()

import os
print(os.listdir(path1))

chat_words = {
    "AFAIK": "as far as i know",
    "AFK": "away from keyboard",
    "ASAP": "as soon as possible",
    "ATM": "at the moment",
    "B4": "before",
    "B4N": "bye for now",
    "BAE": "before anyone else",
    "BB": "bye bye",
    "BBS": "be back soon",
    "BC": "because",
    "BF": "boyfriend",
    "BFF": "best friends forever",
    "BRB": "be right back",
    "BRO": "brother",
    "BTW": "by the way",
    "CYA": "see you",
    "CU": "see you",
    "CUL8R": "see you later",
    "DM": "direct message",
    "DIY": "do it yourself",
    "DND": "do not disturb",
    "EOD": "end of day",
    "F2F": "face to face",
    "FB": "facebook",
    "FF": "follow friday",
    "FOMO": "fear of missing out",
    "FTW": "for the win",
    "FYI": "for your information",
    "GF": "girlfriend",
    "GG": "good game",
    "GL": "good luck",
    "GN": "good night",
    "GM": "good morning",
    "G2G": "got to go",
    "GTG": "got to go",
    "GR8": "great",
    "HAND": "have a nice day",
    "HBD": "happy birthday",
    "HF": "have fun",
    "HMU": "hit me up",
    "ICYMI": "in case you missed it",
    "IDC": "i do not care",
    "IDK": "i do not know",
    "IKR": "i know right",
    "ILY": "i love you",
    "IMHO": "in my humble opinion",
    "IMO": "in my opinion",
    "IRL": "in real life",
    "JK": "just kidding",
    "JSYK": "just so you know",
    "K": "okay",
    "KK": "okay",
    "KTHX": "ok thanks",
    "L8R": "later",
    "LMK": "let me know",
    "LOL": "laughing out loud",
    "LMAO": "laughing my ass off",
    "LMFAO": "laughing my freaking ass off",
    "LTNS": "long time no see",
    "MFW": "my face when",
    "MRW": "my reaction when",
    "MSG": "message",
    "NBD": "no big deal",
    "NGL": "not gonna lie",
    "NM": "not much",
    "NVM": "never mind",
    "NP": "no problem",
    "NSFW": "not safe for work",
    "OFC": "of course",
    "OMG": "oh my god",
    "OMW": "on my way",
    "OP": "original poster",
    "OT": "off topic",
    "OTP": "one true pairing",
    "PPL": "people",
    "PLS": "please",
    "PLZ": "please",
    "POV": "point of view",
    "ROFL": "rolling on the floor laughing",
    "RN": "right now",
    "SMH": "shaking my head",
    "SRY": "sorry",
    "SUP": "what is up",
    "TBH": "to be honest",
    "TBA": "to be announced",
    "TBC": "to be continued",
    "TBD": "to be decided",
    "TGIF": "thank god it is friday",
    "THX": "thanks",
    "TIA": "thanks in advance",
    "TMI": "too much information",
    "TTYL": "talk to you later",
    "TY": "thank you",
    "TYSM": "thank you so much",
    "U": "you",
    "UR": "your",
    "URS": "yours",
    "W8": "wait",
    "WB": "welcome back",
    "WBU": "what about you",
    "WTF": "what the hell",
    "WTH": "what the heck",
    "WYWH": "wish you were here",
    "XOXO": "hugs and kisses",
    "Y": "why",
    "YA": "you",
    "YEA": "yeah",
    "YEP": "yes",
    "YOLO": "you only live once",
    "YW": "you are welcome"
}

import re
import string
import nltk
import emoji
from bs4 import BeautifulSoup
from textblob import TextBlob

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

def chat_conversion(text):
    words = text.split()
    new_text = []

    for w in words:
        if w.upper() in chat_words:
            new_text.append(chat_words[w.upper()])
        else:
            new_text.append(w)

    return " ".join(new_text)

def remove_html(text):
    return BeautifulSoup(text, "html.parser").get_text()

def remove_urls(text):
    return re.sub(r'https?://\S+|www\.\S+', '', text)

def remove_punctuation(text):
    return text.translate(str.maketrans('', '', string.punctuation))

def convert_emojis(text):
    return emoji.demojize(text)

def correct_spelling(text):
    return str(TextBlob(text).correct())

new_df["step1_lower"] =new_df["Content"].apply(lambda x: x.lower())

new_df.head()

new_df["step2_html_removed"] = new_df["step1_lower"].apply(remove_html)

new_df.head()

new_df["step3_url_removed"] = new_df["step2_html_removed"].apply(remove_urls)

new_df.head()

new_df["step4_chat_converted"] = new_df["step3_url_removed"].apply(chat_conversion)

new_df.head()

new_df["step5_emoji_converted"] = new_df["step4_chat_converted"].apply(convert_emojis)

new_df.head()

new_df["step6_no_punctuation"] = new_df["step5_emoji_converted"].apply(remove_punctuation)

!pip install pyspellchecker

from spellchecker import SpellChecker

spell = SpellChecker()

def correct_spelling_fast(text):

    if not isinstance(text, str):
        return ""

    words = text.split()


    misspelled = spell.unknown(words)


    corrections = {word: spell.correction(word) for word in misspelled}


    corrected_words = [
        corrections[word] if word in corrections and corrections[word] is not None else word
        for word in words
    ]

    return " ".join(corrected_words)

new_df["step7_spell_correct"] = new_df["step6_no_punctuation"].apply(correct_spelling_fast)

# from nltk.tokenize import word_tokenize

# new_df["step8_tokens"] = new_df["step7_spell_correct"].apply(word_tokenize)

from nltk.tokenize import word_tokenize

new_df["step8_tokens"] = new_df["step6_no_punctuation"].apply(word_tokenize)

new_df["step8_tokens"].sample(10)

from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

keep_words = {

"no","not","nor","never","none","nothing","nowhere","neither",

"don't","doesn't","didn't","can't","couldn't","won't","wouldn't",
"shouldn't","mustn't","isn't","aren't","wasn't","weren't",
"haven't","hasn't","hadn't","ain't",

"i","me","my","mine","myself",
"we","us","our","ours","ourselves",
"you","your","yours","yourself","yourselves",
"he","him","his","himself",
"she","her","hers","herself",
"they","them","their","theirs","themselves"
}

stop_words = stop_words - keep_words

def remove_stopwords(tokens):
    return [word for word in tokens if word not in stop_words]

new_df["step9_no_stopwords"] = new_df["step8_tokens"].apply(remove_stopwords)

from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

def apply_lemmatization(tokens):
    return [lemmatizer.lemmatize(word, pos='v') for word in tokens]

new_df["step10_lemmataization"] = new_df["step9_no_stopwords"].apply(apply_lemmatization)

new_df["step10_lemmataization"].sample(10)

new_df.head()

def tokens_to_sentence(tokens):

    return " ".join(tokens)

new_df["text"] = new_df["step10_lemmataization"].apply(tokens_to_sentence)

new_df.head()

from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(
    ngram_range=(1,2),
    max_features=5000
)

X1 = vectorizer.fit_transform(new_df["text"])

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    ngram_range=(1,2),
    max_features=5000
)

X2 = vectorizer.fit_transform(new_df["text"])

new_df["Label"].value_counts()

from sklearn.model_selection import train_test_split

X1_train, X1_test, y1_train, y1_test = train_test_split(
    X1,
    new_df["Label"],
    test_size=0.2,
    random_state=42
)

X2_train, X2_test, y2_train, y2_test = train_test_split(
    X2,
    new_df["Label"],
    test_size=0.2,
    random_state=42
)

X = df["text"]
y = df["Label"]

import multiprocessing
cores = multiprocessing.cpu_count()

print(cores)

sentences = new_df["step10_lemmataization"].tolist()

from gensim.models import Word2Vec
w2v_model = Word2Vec(
    sentences=sentences,
    vector_size=200,
    window=5,
    min_count=2,
    workers=cores,
    sg=1,
    epochs=5
)

def get_vector(tokens, model):

    vectors = []

    for word in tokens:
        if word in model.wv:
            vectors.append(model.wv[word])

    if len(vectors) == 0:
        return np.zeros(model.vector_size)

    return np.mean(vectors, axis=0)

X_w2v = np.array([get_vector(tokens, w2v_model) for tokens in sentences])

from sklearn.model_selection import train_test_split

X_train_w2v, X_test_w2v, y_train_w2v, y_test_w2v = train_test_split(
    X_w2v,
    new_df["Label"],
    test_size=0.2,
    random_state=42,
    stratify=new_df["Label"]
)

from gensim.models import Word2Vec

w2v_model = Word2Vec(
    train_tokens,
    vector_size=100,
    window=5,
    min_count=2,
    workers=4
)

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

bnb1= BernoulliNB()
bnb1.fit(X_train_w2v, y_train_w2v)

y_pred = bnb1.predict(X_test_w2v)

print("Accuracy:", accuracy_score(y_test_w2v, y_pred))
print(classification_report(y_test_w2v, y_pred))

bnb2= BernoulliNB()
bnb2.fit(X1_train, y1_train)

y_pred2 = bnb2.predict(X1_test)

print("Accuracy:", accuracy_score(y1_test, y_pred2))
print(classification_report(y1_test, y_pred2))

bnb3= BernoulliNB()
bnb3.fit(X2_train, y2_train)

y_pred3=bnb3.predict(X2_test)

print("Accuracy:", accuracy_score(y2_test, y_pred3))
print(classification_report(y2_test, y_pred3))

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

tokenizer = Tokenizer(num_words=10000)

tokenizer.fit_on_texts(new_df["text"])

sequences = tokenizer.texts_to_sequences(new_df["text"])

max_len = 100

X_seq = pad_sequences(sequences, maxlen=max_len)

X_train_lstm, X_test_lstm, y_train_lstm, y_test_lstm = train_test_split(
    X_seq,
    new_df["Label"],
    test_size=0.2,
    random_state=42,
    stratify=new_df["Label"]
)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout, Input

model = Sequential()

model.add(Input(shape=(100,)))


model.add(Embedding(
    input_dim=10000,
    output_dim=128
))


model.add(LSTM(128, return_sequences=True))
model.add(LSTM(64, return_sequences=True))
model.add(LSTM(32))


model.add(Dropout(0.3))


model.add(Dense(1, activation="sigmoid"))

model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

history = model.fit(
    X_train_lstm,
    y_train_lstm,
    epochs=5,
    batch_size=32,
    validation_data=(X_test_lstm, y_test_lstm)
)

loss, accuracy = model.evaluate(X_test_lstm, y_test_lstm)

print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

y_pred= (model.predict(X_test_lstm) > 0.5).astype(int)
print("Predictions (0=Non-Hate, 1=Hate):")
print(y_pred[:10])
def predict_hate(text):
    seq = tokenizer.texts_to_sequences([text])
    seq = pad_sequences(seq, maxlen=100)
    pred = model.predict(seq)
    return int(pred > 0.5)

sentence = "you are a good boy"
print("Prediction for sentence:", predict_hate(sentence))

from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

y_pred_prob = model.predict(X_test_lstm).ravel()

fpr, tpr, thresholds = roc_curve(y_test_lstm, y_pred_prob)
roc_auc = auc(fpr, tpr)
print("AUC:", roc_auc)

plt.figure(figsize=(8,6))
plt.plot(fpr, tpr, color='blue', lw=2, label='ROC curve (AUC = %0.2f)' % roc_auc)
plt.plot([0,1], [0,1], color='red', lw=2, linestyle='--', label='Random')
plt.xlim([0.0,1.0])
plt.ylim([0.0,1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend(loc='lower right')
plt.show()

import numpy as np

J = tpr - fpr
ix = np.argmax(J)

best_threshold = thresholds[ix]

print("Best Threshold:", best_threshold)
print("TPR:", tpr[ix])
print("FPR:", fpr[ix])